In [86]:
import pandas as pd
import numpy as np

In [87]:
data = pd.read_csv('data/train.csv')
cols1 = data.columns
data = data.rename({'1stFlrSF': 'FstFlrSF', 
              '2ndFlrSF': 'SndFlrSF', 
              '3SsnPorch': 'ThirdSsnPorch'}, axis=1)

In [88]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', 'FstFlrSF', 'SndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', 'ThirdSsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='str')

In [89]:
categeorical_columns = [column for column in data.columns if data[column].dtype == 'str']
quantitive_columns = [column for column in data.columns if data[column].dtype != 'str' and column != "SalePrice"]
print('categorical_columns =', categeorical_columns)
print('quantitive_columns =', quantitive_columns)

categorical_columns = ['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']
quantitive_columns = ['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'FstFlrSF', 'SndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', 'ThirdSsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']

In [90]:
missing_values = data.isna().sum().sort_values(ascending=False)
missing_values_columns = missing_values[missing_values > 0]
missing_values_columns

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageYrBlt       81
GarageCond        81
GarageType        81
GarageFinish      81
GarageQual        81
BsmtFinType2      38
BsmtExposure      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
dtype: int64

In [91]:
for i in categeorical_columns:
    if i not in missing_values_columns:
        print(i)

MSZoning
Street
LotShape
LandContour
Utilities
LotConfig
LandSlope
Neighborhood
Condition1
Condition2
BldgType
HouseStyle
RoofStyle
RoofMatl
Exterior1st
Exterior2nd
ExterQual
ExterCond
Foundation
Heating
HeatingQC
CentralAir
KitchenQual
Functional
PavedDrive
SaleType
SaleCondition

# Preprocessing test

In [92]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import TargetEncoder

In [93]:
pd.DataFrame(TargetEncoder(target_type='continuous').fit_transform(data[categeorical_columns], data.iloc[::, -1]), columns=categeorical_columns)

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,193874.697890,183593.132407,185768.972117,166016.357139,182855.598219,183411.337363,179339.455262,182222.881691,198797.969664,187630.045576,...,205633.218451,203377.285856,190439.159693,190894.420550,189219.857021,182721.365655,189797.162931,184352.689391,175289.839432,176921.239424
1,193874.697890,183593.132407,185768.972117,166016.357139,182855.598219,183411.337363,181712.885400,182222.881691,227272.547217,139526.937450,...,205633.218451,203377.285856,190439.159693,190894.420550,189219.857021,182721.365655,189797.162931,184352.689391,175289.839432,176921.239424
2,190572.390070,180541.584268,182777.034405,206881.099678,179440.241890,180387.237158,175524.399120,179499.148672,195739.153601,183369.814334,...,201847.046786,201450.165259,186536.523790,187104.262118,186030.588293,179730.595634,186520.996421,181603.039983,172840.361184,174489.219366
3,188619.374331,179124.733126,181274.254790,200969.271504,178768.209785,178908.996192,179158.853419,178461.847708,209061.635541,183020.463140,...,133588.581645,142793.972885,185846.641262,186018.553346,184297.435404,178785.401923,185818.989916,180093.455321,172144.821738,135281.895599
4,190572.390070,180541.584268,182777.034405,206881.099678,179440.241890,180387.237158,178604.674474,179499.148672,321656.242370,183369.814334,...,201847.046786,201450.165259,186536.523790,187104.262118,186030.588293,179730.595634,186520.996421,181603.039983,172840.361184,174489.219366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,188619.374331,179124.733126,181274.254790,165094.151225,178768.209785,178908.996192,175097.282328,178461.847708,194355.060539,183020.463140,...,200534.317133,200913.527570,185846.641262,186018.553346,184297.435404,178785.401923,185818.989916,180093.455321,172144.821738,174654.977852
1456,189850.901210,179448.056389,182018.434906,163361.862589,177858.690494,179336.633410,176020.940845,178096.934034,187307.954974,182326.756095,...,200525.088826,140215.532419,185317.686565,185992.216787,184433.377633,178706.529084,148729.798154,180312.462833,172028.117306,173087.514175
1457,189850.901210,179448.056389,182018.434906,163361.862589,177858.690494,179336.633410,176020.940845,178096.934034,218122.385405,182326.756095,...,200525.088826,200345.371751,185317.686565,185992.216787,184433.377633,178706.529084,175125.638469,152484.676578,172028.117306,173087.514175
1458,193874.697890,183593.132407,185768.972117,166016.357139,182855.598219,183411.337363,179339.455262,182222.881691,146213.310688,187630.045576,...,205633.218451,142251.911806,190439.159693,190894.420550,189219.857021,182721.365655,189797.162931,184352.689391,175289.839432,176921.239424
1459,192046.452644,182943.017368,185391.193913,165410.127267,182000.149430,182710.935135,178657.072388,181497.017894,125322.221633,186099.497639,...,205727.042161,245495.159598,189271.468802,189381.314826,188148.417761,182081.511596,189750.847086,183866.837987,174759.616486,176897.690687

In [94]:
pd.DataFrame(StandardScaler().fit_transform(SimpleImputer(strategy='median').fit_transform(data[quantitive_columns])), columns=quantitive_columns)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,ThirdSsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,-1.730865,0.073375,-0.220875,-0.207142,0.651479,-0.517200,1.050994,0.878668,0.514104,0.575425,...,0.351000,-0.752176,0.216503,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,0.138777
1,-1.728492,-0.872563,0.460320,-0.091886,-0.071836,2.179628,0.156734,-0.429577,-0.570750,1.171992,...,-0.060731,1.626195,-0.704483,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-0.489110,-0.614439
2,-1.726120,0.073375,-0.084636,0.073480,0.651479,-0.517200,0.984752,0.830215,0.325915,0.092907,...,0.631726,-0.752176,-0.070361,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,0.990891,0.138777
3,-1.723747,0.309859,-0.447940,-0.096897,0.651479,-0.517200,-1.863632,-0.720298,-0.570750,-0.499274,...,0.790804,-0.752176,-0.176048,4.092524,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,-1.367655
4,-1.721374,0.073375,0.641972,0.375148,1.374795,-0.517200,0.951632,0.733308,1.366489,0.463568,...,1.698485,0.780197,0.563760,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,2.100892,0.138777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.721374,0.073375,-0.357114,-0.260560,-0.071836,-0.517200,0.918511,0.733308,-0.570750,-0.973018,...,-0.060731,-0.752176,-0.100558,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,0.620891,-0.614439
1456,1.723747,-0.872563,0.687385,0.266407,-0.071836,0.381743,0.222975,0.151865,0.087911,0.759659,...,0.126420,2.033231,-0.704483,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,1.645210
1457,1.726120,0.309859,-0.175462,-0.147810,0.651479,3.078570,-1.002492,1.024029,-0.570750,-0.369871,...,-1.033914,-0.752176,0.201405,-0.359325,-0.116339,-0.270208,-0.068692,4.953112,-0.489110,1.645210
1458,1.728492,-0.872563,-0.084636,-0.080160,-0.795151,0.381743,-0.704406,0.539493,-0.570750,-0.865548,...,-1.090059,2.168910,-0.704483,1.473789,-0.116339,-0.270208,-0.068692,-0.087688,-0.859110,1.645210
1459,1.730865,-0.872563,0.233255,-0.058112,-0.795151,0.381743,-0.207594,-0.962566,-0.570750,0.847389,...,-0.921624,5.121921,0.322190,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-0.119110,0.138777

In [95]:
categorical_columns = [
    "MSZoning",
    "Street",
    "Alley",
    "LotShape",
    "LandContour",
    "Utilities",
    "LotConfig",
    "LandSlope",
    "Neighborhood",
    "Condition1",
    "Condition2",
    "BldgType",
    "HouseStyle",
    "RoofStyle",
    "RoofMatl",
    "Exterior1st",
    "Exterior2nd",
    "MasVnrType",
    "ExterQual",
    "ExterCond",
    "Foundation",
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2",
    "Heating",
    "HeatingQC",
    "CentralAir",
    "Electrical",
    "KitchenQual",
    "Functional",
    "FireplaceQu",
    "GarageType",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
    "PavedDrive",
    "PoolQC",
    "Fence",
    "MiscFeature",
    "SaleType",
    "SaleCondition",
]
quantitive_columns = [
    "Id",
    "MSSubClass",
    "LotFrontage",
    "LotArea",
    "OverallQual",
    "OverallCond",
    "YearBuilt",
    "YearRemodAdd",
    "MasVnrArea",
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "FstFlrSF",
    "SndFlrSF",
    "LowQualFinSF",
    "GrLivArea",
    "BsmtFullBath",
    "BsmtHalfBath",
    "FullBath",
    "HalfBath",
    "BedroomAbvGr",
    "KitchenAbvGr",
    "TotRmsAbvGrd",
    "Fireplaces",
    "GarageYrBlt",
    "GarageCars",
    "GarageArea",
    "WoodDeckSF",
    "OpenPorchSF",
    "EnclosedPorch",
    "ThirdSsnPorch",
    "ScreenPorch",
    "PoolArea",
    "MiscVal",
    "MoSold",
    "YrSold",
]

numeric_transformer = Pipeline(steps=[("imputer", SimpleImputer(strategy="median")), ("scaler", StandardScaler())])


categorical_transformer = Pipeline(steps=[("target_enc", TargetEncoder(target_type="continuous", smooth="auto"))])


preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, quantitive_columns),
        ("cat", categorical_transformer, categeorical_columns),
    ],
    remainder="drop",
)

In [96]:
preprocessor.fit_transform(data.iloc[::, :-1:], data.iloc[::, -1])

array([[-1.73086488e+00,  7.33749635e-02, -2.20875089e-01, ...,
         1.81026071e+05,  1.72891930e+05,  1.74829470e+05],
       [-1.72849220e+00, -8.72562756e-01,  4.60319735e-01, ...,
         1.82498040e+05,  1.74803560e+05,  1.76728121e+05],
       [-1.72611953e+00,  7.33749635e-02, -8.46361241e-02, ...,
         1.82498040e+05,  1.74803560e+05,  1.76728121e+05],
       ...,
       [ 1.72611953e+00,  3.09859393e-01, -1.75462101e-01, ...,
         1.51939177e+05,  1.73514567e+05,  1.74892936e+05],
       [ 1.72849220e+00, -8.72562756e-01, -8.46361241e-02, ...,
         1.83028296e+05,  1.73514567e+05,  1.74892936e+05],
       [ 1.73086488e+00, -8.72562756e-01,  2.33254794e-01, ...,
         1.82220126e+05,  1.72612078e+05,  1.74557973e+05]],
      shape=(1460, 80))

# Import preprocessing pipeline

In [97]:
from preprocessing import preprocessor

# data split

In [98]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    data.iloc[::, :-1:], data.iloc[::, -1], test_size=0.33, random_state=42)

In [99]:
X_train.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', 'FstFlrSF', 'SndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', 'ThirdSsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='str')

# Model

In [100]:
from sklearn.ensemble import GradientBoostingRegressor

In [101]:
model_pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', GradientBoostingRegressor())
])

In [102]:
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Id', 'MSSubClass',
                                                   'LotFrontage', 'LotArea',
                                                   'OverallQual', 'OverallCond',
                                                   'YearBuilt', 'YearRemodAdd',
                                                   'MasVnrArea', 'BsmtFinSF1',
                                                   'BsmtFinSF2', 'BsmtUnfSF',
                                                   'TotalBsmtSF', 'FstFlrSF',
                                                   'SndFlrSF', 'L...
                                                   'LotConfig', 'LandSlope',
                                                   'Neighborhood', 'Condition1',
                                                   'Condition2', 'BldgType',
                                                   'HouseStyle', 'RoofStyle',
                                                   'RoofMatl', 'Exterior1st',
                                                   'Exterior2nd', 'MasVnrType',
                                                   'ExterQual', 'ExterCond',
                                                   'Foundation', 'BsmtQual',
                                                   'BsmtCond', 'BsmtExposure',
                                                   'BsmtFinType1',
                                                   'BsmtFinType2', 'Heating',
                                                   'HeatingQC', 'CentralAir',
                                                   'Electrical', ...])])),
                ('model', GradientBoostingRegressor())])

In [103]:
preds = model_pipeline.predict(X_test)
preds

array([148116.29038537, 349842.21519715, 119579.61637398, 138520.82433482,
       338210.54053271,  74970.10025241, 219495.01975277, 137610.36253108,
        74636.93257419, 130296.84186838, 147550.64659318, 124222.24379636,
       119296.79402844, 202138.05386852, 171757.66552054, 136312.80939554,
       196756.1020071 , 139312.63616316, 119009.77797889, 221554.09359026,
       173971.87240144, 220178.26340123, 168612.97020395, 124244.71680591,
       199207.37617336, 160482.67901282, 196744.10301254, 124323.77495005,
       174968.73660222, 196027.80679522, 120711.14892607, 259326.07334842,
       227040.98484279, 110607.38755893, 245026.16379406, 151766.62990844,
       134113.24309421, 212449.92198513, 310135.15748683,  96682.08428136,
       126929.63552492, 239461.62560861, 116019.45458703, 369947.04147926,
       125607.30481038, 127093.40161009, 112933.68886   , 124780.6660835 ,
       450845.05552971, 128550.42908689, 123127.86955058, 196716.37190578,
       109424.94198824, 359880.04466293, 157625.33245716, 245366.48131977,
       192701.9315829 , 150985.6486035 , 138268.97742494, 108588.10924755,
        64346.77769984, 156483.4105299 , 311315.27856305, 285501.61202303,
       303155.82316235, 217848.79979382, 107734.80848658, 310217.50903788,
       109582.52832314, 157970.78342448, 129227.81889155, 119402.34238346,
       107140.94906798,  88257.58156741, 437165.82164506, 196047.85736831,
       309950.61241718, 310896.16124215, 140736.48017313, 124844.96710531,
       109661.4661336 ,  73880.02844298, 125568.13568136,  99403.96876146,
       148681.25821883, 129223.39799749, 259038.75404311, 219821.94505818,
       146302.90355764, 181279.7412931 , 158655.18437291, 160944.14969153,
       125379.31838979, 264850.61243447, 114985.29714476, 179160.78605866,
       178984.29894458, 175561.36325443, 207955.98189822, 252551.84160669,
       162867.3294641 , 206438.44193846, 240135.41473768, 145951.43313086,
       195303.17975777, 153836.72883109, 152154.61468681, 290627.09396456,
       144656.92377118, 165020.32339955,  55544.53451348, 134770.82527239,
       136782.99279661, 124044.16730044, 200434.90448114, 113562.18414762,
       101760.66536324, 110068.46327055, 123436.92101222, 264245.23984648,
       142848.96521426, 146096.89969414, 176751.55610758, 180009.92415428,
       185725.65680281, 127186.71115766, 245694.17783859, 103841.85690092,
       149847.62110094, 180600.40509175, 190684.99990417, 367298.79603945,
       197091.11406612, 115612.16458611,  64101.66733474, 354014.49791362,
       427143.08449955, 135684.03075672, 237412.11024042, 505673.6104617 ,
       313327.02157262, 131574.97033287, 179885.06146253, 152891.3462585 ,
       161105.3848944 , 125389.26771278, 234214.56323881, 190947.34014216,
       137140.5755472 ,  71046.58535422, 117377.91755019, 142377.13372199,
       294082.48065053, 142960.56642116,  92300.96016695, 119172.94344864,
       145159.26697863, 147368.06905638,  93153.79517495, 129402.6960148 ,
       225582.24160831, 151029.92638675, 321218.85271603, 144830.58289732,
       111328.87787972, 115590.25112368, 224786.30166023, 350854.0710687 ,
       432278.8735519 , 250661.18421794, 386205.33804458,  88933.52234912,
       111628.10835965, 139953.5926018 , 364640.07901591, 153290.57889909,
       119249.68197277, 200394.09140678, 119753.13602298, 161727.93649235,
       176390.65733886, 104408.58621139, 135718.36393804, 141897.84307034,
       252340.3413311 , 148910.51819772, 270116.52325384, 209787.85544569,
       187290.58352857,  83193.56426244, 111527.67955661, 108607.31123884,
       146928.69812361, 145861.53423057, 177663.37818653, 160323.88398365,
       232750.14559543,  84330.4343302 , 203632.17785729, 138297.14360417,
       219776.03682289, 195750.05421311, 124424.61345383, 340079.23758907,
       189367.0676253 , 124952.46542406, 240886.90899216, 138374.80732466,
       146831.86044398, 117845.51818465, 243338.14388672, 141191.6347188 ,
       113146.64236362, 151665.06436701, 217674.31423859, 277763.14307003,
       172842.50098734, 150505.99634765, 138472.31411779, 140419.64076198,
       143568.57724479, 226161.28439025, 208433.8003015 ,  98239.90775252,
       251778.51707326, 149842.98213971, 102594.54104626,  99247.21655547,
       171485.70172129, 103828.90626981,  99586.46255499, 181101.13095404,
       120645.06871369, 138259.94068664, 220454.18052699, 133042.77192444,
       192489.11035796, 147286.07987134, 228966.51051975, 132217.60880711,
       114816.42941789, 257165.01904237, 205416.80463674, 397331.13270346,
       201784.48995759, 129859.0073007 , 157911.9924159 , 179522.6443827 ,
       150490.89093713,  98918.81778189, 190049.92970106, 173525.3608041 ,
       125125.98752947,  91227.42765114, 134970.19870453, 144233.53386971,
       105661.03974447, 105636.03465679, 172749.05799049, 261008.67685593,
       311122.24158142, 177195.23167819, 138265.58094475, 227012.71689509,
       302746.79346196, 213863.13716778, 163485.34699369, 142675.18754198,
       120003.86971322, 173871.42573677, 400462.21166381, 232761.37841564,
       224477.00685307,  87208.08814778, 107019.92900211, 130589.99738004,
       147240.08706449, 299902.24347588, 241973.75364767, 137829.04898814,
       199184.89708583, 109919.20285929, 191379.2945713 , 107859.19498563,
       318033.96132909, 185229.47239746, 214924.6911754 , 113850.58190384,
       252431.70072974, 183617.17230076, 103503.18077129, 117983.40140123,
       149533.32177665, 180047.90190362, 100159.18684374, 144463.25137547,
       137573.65416508, 144278.74542126, 184320.42118587, 105271.77701276,
       183239.28861824, 238744.61060775, 119045.52812753, 150144.4312272 ,
       181612.18858248, 186285.37855763, 160969.26910205, 223119.24274239,
       239835.47029756, 129881.80822902, 146671.5768165 , 203163.09931553,
       105988.62175791, 153229.20445058, 126140.91581593, 178945.71023871,
       181636.7903382 , 169700.77635904, 286072.83719751,  88257.58156741,
       230861.41501528, 143390.80511179, 130833.41098158,  94270.36869033,
       188370.01514514, 165974.68901351, 127242.68046543, 193994.77207026,
       161820.74711175,  97160.41402663, 160338.87569322, 150722.63757105,
       130934.39727643, 201210.65751633, 163962.60155475, 128825.83231461,
       135615.54978837,  96999.29671806,  88940.26116713, 217011.08133936,
       181482.85067269, 136215.5597035 , 124385.01230073, 181972.93613591,
       227216.14515246, 340160.14450395, 369560.30765889, 118083.11160952,
       238314.94827089, 121421.08589862, 318052.23791949, 397579.21209777,
       322263.74338952, 164065.90531588, 266729.33099244, 139550.30684146,
       120548.46858113,  93069.46705209, 200751.8776921 , 358312.29593858,
       205977.77148475, 133834.14900322, 254053.46334004, 220189.46825649,
       127572.17071567, 187094.12426195, 172135.11975273, 108099.6031447 ,
       130231.67574552, 154177.65936545, 119348.64269428, 176331.04591797,
       131166.04604864, 213704.89341216, 153679.14554347, 125163.45889527,
       211032.06118883, 191333.80863085, 101067.18415728, 212308.12713875,
       143240.47767122, 177897.44853648, 196176.22374479, 164208.03664394,
       135149.83915086, 224887.46744407, 140041.40397688, 123253.33233622,
       290009.595179  , 178405.38679324, 123857.59484577, 152700.73856781,
       133121.21394791, 371989.72932511, 138960.24791846, 404458.47702769,
       124616.40450926, 168524.14619086, 167450.54357333, 131315.95325258,
       161703.86540578, 381911.55412587, 102374.65017421, 150602.50574782,
       154236.65137877, 101472.47233526, 197110.26830152, 147438.16616476,
       239123.2872841 , 206829.44293393, 215804.49696183, 200252.60229563,
        80040.4260728 , 321327.88430315, 139578.44350003, 362502.20181308,
       141305.94717651, 371759.77615703, 271480.22383607, 126484.75792815,
       229355.54337453, 234844.58765792, 204987.64976643, 182458.38938058,
       262735.81460048, 106881.61897004, 212422.89756237, 171196.09810582,
       188405.52590818, 234820.37851564, 110293.14577686, 151325.15372594,
       182308.67226198, 139365.23823731, 121088.40048215, 200178.06245639,
       129616.99856913, 447605.29992246, 184974.10995062, 133724.46970672,
       200304.31953504, 331019.85448892, 203107.84614445, 156131.62956669,
       196118.26438165, 136585.52120283, 181583.46670383, 217788.75740514,
       138398.82167573, 149160.29633791, 119705.16423458, 169483.83954737,
       226735.8373157 , 155891.09542005,  96716.16821463, 191727.12751348,
       329511.38377845, 338264.61225381, 251770.19521393, 155173.02198461,
       134521.08558989, 113604.91216125, 165851.10491213, 227668.67895819,
       169030.29911549, 423779.71730136, 187825.2946707 , 187094.12426195,
       111430.57675054, 256879.9610593 , 120066.33160673, 110480.86586238,
       131166.08867221, 122418.2816765 , 205710.26579801, 267769.23022108,
       131123.87470481, 118946.07069258, 114972.55201216, 213281.43339207,
       143444.02482218, 174966.84775653])

In [104]:
abs(np.log(y_test) - np.log(preds)).mean()

np.float64(0.0909481621487459)

# Saving model

In [105]:
import joblib

metadata = {
    'version': '1.0.0',
    'features': X_train.columns
}

bundle = {
    "pipeline": model_pipeline,
    "metadata": metadata
}

joblib.dump(bundle, "../artifact/model_1.0.joblib")

['../artifact/model_1.0.joblib']

In [106]:
_ = [print(i, ':', X_train[i].dtype) for i in X_train.columns.to_list()]

Id : int64
MSSubClass : int64
MSZoning : str
LotFrontage : float64
LotArea : int64
Street : str
Alley : str
LotShape : str
LandContour : str
Utilities : str
LotConfig : str
LandSlope : str
Neighborhood : str
Condition1 : str
Condition2 : str
BldgType : str
HouseStyle : str
OverallQual : int64
OverallCond : int64
YearBuilt : int64
YearRemodAdd : int64
RoofStyle : str
RoofMatl : str
Exterior1st : str
Exterior2nd : str
MasVnrType : str
MasVnrArea : float64
ExterQual : str
ExterCond : str
Foundation : str
BsmtQual : str
BsmtCond : str
BsmtExposure : str
BsmtFinType1 : str
BsmtFinSF1 : int64
BsmtFinType2 : str
BsmtFinSF2 : int64
BsmtUnfSF : int64
TotalBsmtSF : int64
Heating : str
HeatingQC : str
CentralAir : str
Electrical : str
FstFlrSF : int64
SndFlrSF : int64
LowQualFinSF : int64
GrLivArea : int64
BsmtFullBath : int64
BsmtHalfBath : int64
FullBath : int64
HalfBath : int64
BedroomAbvGr : int64
KitchenAbvGr : int64
KitchenQual : str
TotRmsAbvGrd : int64
Functional : str
Fireplaces : int64
FireplaceQu : str
GarageType : str
GarageYrBlt : float64
GarageFinish : str
GarageCars : int64
GarageArea : int64
GarageQual : str
GarageCond : str
PavedDrive : str
WoodDeckSF : int64
OpenPorchSF : int64
EnclosedPorch : int64
ThirdSsnPorch : int64
ScreenPorch : int64
PoolArea : int64
PoolQC : str
Fence : str
MiscFeature : str
MiscVal : int64
MoSold : int64
YrSold : int64
SaleType : str
SaleCondition : str

In [107]:
loaded_model = joblib.load("../artifact/model_1.0.joblib")

In [108]:
loaded_model

{'pipeline': Pipeline(steps=[('preprocessing',
                  ColumnTransformer(transformers=[('num',
                                                   Pipeline(steps=[('imputer',
                                                                    SimpleImputer(strategy='median')),
                                                                   ('scaler',
                                                                    StandardScaler())]),
                                                   ['Id', 'MSSubClass',
                                                    'LotFrontage', 'LotArea',
                                                    'OverallQual', 'OverallCond',
                                                    'YearBuilt', 'YearRemodAdd',
                                                    'MasVnrArea', 'BsmtFinSF1',
                                                    'BsmtFinSF2', 'BsmtUnfSF',
                                                    'TotalBsmtSF', 'FstFlrSF',
                                                    'SndFlrSF', 'L...
                                                    'LotConfig', 'LandSlope',
                                                    'Neighborhood', 'Condition1',
                                                    'Condition2', 'BldgType',
                                                    'HouseStyle', 'RoofStyle',
                                                    'RoofMatl', 'Exterior1st',
                                                    'Exterior2nd', 'MasVnrType',
                                                    'ExterQual', 'ExterCond',
                                                    'Foundation', 'BsmtQual',
                                                    'BsmtCond', 'BsmtExposure',
                                                    'BsmtFinType1',
                                                    'BsmtFinType2', 'Heating',
                                                    'HeatingQC', 'CentralAir',
                                                    'Electrical', ...])])),
                 ('model', GradientBoostingRegressor())]),
 'metadata': {'version': '1.0.0',
  'features': Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
         'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
         'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
         'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
         'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
         'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
         'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
         'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
         'HeatingQC', 'CentralAir', 'Electrical', 'FstFlrSF', 'SndFlrSF',
         'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
         'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
         'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
         'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
         'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
         'EnclosedPorch', 'ThirdSsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
         'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
         'SaleCondition'],
        dtype='str')}}

In [109]:
print(loaded_model['pipeline'].predict(X_test.head(1)),
loaded_model['pipeline'].predict(X_test.head(1)))

[148116.29038537] [148116.29038537]

# Example for fastapi test

In [110]:
_ = [print(f'"{key}" : "{value}",') if isinstance(value, str) else print(f'"{key}" : {value},')  for (key, value) in zip(X_train.columns, X_train.loc[0])]

"Id" : 1,
"MSSubClass" : 60,
"MSZoning" : "RL",
"LotFrontage" : 65.0,
"LotArea" : 8450,
"Street" : "Pave",
"Alley" : nan,
"LotShape" : "Reg",
"LandContour" : "Lvl",
"Utilities" : "AllPub",
"LotConfig" : "Inside",
"LandSlope" : "Gtl",
"Neighborhood" : "CollgCr",
"Condition1" : "Norm",
"Condition2" : "Norm",
"BldgType" : "1Fam",
"HouseStyle" : "2Story",
"OverallQual" : 7,
"OverallCond" : 5,
"YearBuilt" : 2003,
"YearRemodAdd" : 2003,
"RoofStyle" : "Gable",
"RoofMatl" : "CompShg",
"Exterior1st" : "VinylSd",
"Exterior2nd" : "VinylSd",
"MasVnrType" : "BrkFace",
"MasVnrArea" : 196.0,
"ExterQual" : "Gd",
"ExterCond" : "TA",
"Foundation" : "PConc",
"BsmtQual" : "Gd",
"BsmtCond" : "TA",
"BsmtExposure" : "No",
"BsmtFinType1" : "GLQ",
"BsmtFinSF1" : 706,
"BsmtFinType2" : "Unf",
"BsmtFinSF2" : 0,
"BsmtUnfSF" : 150,
"TotalBsmtSF" : 856,
"Heating" : "GasA",
"HeatingQC" : "Ex",
"CentralAir" : "Y",
"Electrical" : "SBrkr",
"FstFlrSF" : 856,
"SndFlrSF" : 854,
"LowQualFinSF" : 0,
"GrLivArea" : 1710,
"BsmtFullBath" : 1,
"BsmtHalfBath" : 0,
"FullBath" : 2,
"HalfBath" : 1,
"BedroomAbvGr" : 3,
"KitchenAbvGr" : 1,
"KitchenQual" : "Gd",
"TotRmsAbvGrd" : 8,
"Functional" : "Typ",
"Fireplaces" : 0,
"FireplaceQu" : nan,
"GarageType" : "Attchd",
"GarageYrBlt" : 2003.0,
"GarageFinish" : "RFn",
"GarageCars" : 2,
"GarageArea" : 548,
"GarageQual" : "TA",
"GarageCond" : "TA",
"PavedDrive" : "Y",
"WoodDeckSF" : 0,
"OpenPorchSF" : 61,
"EnclosedPorch" : 0,
"ThirdSsnPorch" : 0,
"ScreenPorch" : 0,
"PoolArea" : 0,
"PoolQC" : nan,
"Fence" : nan,
"MiscFeature" : nan,
"MiscVal" : 0,
"MoSold" : 2,
"YrSold" : 2008,
"SaleType" : "WD",
"SaleCondition" : "Normal",

In [111]:
[X_train[column].unique() for column in categeorical_columns]

[<StringArray>
 ['RL', 'RM', 'C (all)', 'RH', 'FV']
 Length: 5, dtype: str,
 <StringArray>
 ['Pave', 'Grvl']
 Length: 2, dtype: str,
 <StringArray>
 [nan, 'Grvl', 'Pave']
 Length: 3, dtype: str,
 <StringArray>
 ['Reg', 'IR1', 'IR3', 'IR2']
 Length: 4, dtype: str,
 <StringArray>
 ['Lvl', 'Bnk', 'Low', 'HLS']
 Length: 4, dtype: str,
 <StringArray>
 ['AllPub', 'NoSeWa']
 Length: 2, dtype: str,
 <StringArray>
 ['Inside', 'Corner', 'FR2', 'CulDSac', 'FR3']
 Length: 5, dtype: str,
 <StringArray>
 ['Gtl', 'Mod', 'Sev']
 Length: 3, dtype: str,
 <StringArray>
 [  'NAmes', 'Mitchel', 'Somerst', 'Edwards',   'SWISU', 'CollgCr', 'StoneBr',
  'Veenker',  'Timber', 'Gilbert', 'SawyerW', 'BrkSide',  'NWAmes', 'OldTown',
   'IDOTRR', 'NridgHt', 'NoRidge',  'Sawyer', 'ClearCr', 'Crawfor',  'BrDale',
  'Blmngtn', 'MeadowV', 'NPkVill', 'Blueste']
 Length: 25, dtype: str,
 <StringArray>
 ['Feedr', 'Norm', 'RRAn', 'Artery', 'PosN', 'RRNn', 'RRAe', 'PosA', 'RRNe']
 Length: 9, dtype: str,
 <StringArray>
 ['Norm', 'Feedr', 'RRAe', 'PosN', 'Artery', 'RRAn']
 Length: 6, dtype: str,
 <StringArray>
 ['1Fam', 'TwnhsE', 'Duplex', 'Twnhs', '2fmCon']
 Length: 5, dtype: str,
 <StringArray>
 ['SFoyer', '1Story', '2Story', 'SLvl', '1.5Fin', '2.5Unf', '1.5Unf', '2.5Fin']
 Length: 8, dtype: str,
 <StringArray>
 ['Gable', 'Hip', 'Mansard', 'Flat', 'Shed', 'Gambrel']
 Length: 6, dtype: str,
 <StringArray>
 ['CompShg', 'Metal', 'Tar&Grv', 'WdShake', 'ClyTile', 'WdShngl', 'Roll']
 Length: 7, dtype: str,
 <StringArray>
 ['MetalSd', 'VinylSd', 'HdBoard', 'Wd Sdng', 'CemntBd', 'Plywood',  'Stucco',
  'BrkFace', 'AsbShng', 'WdShing', 'BrkComm',  'CBlock', 'AsphShn',   'Stone']
 Length: 14, dtype: str,
 <StringArray>
 ['MetalSd', 'VinylSd', 'HdBoard', 'Wd Sdng', 'CmentBd', 'Plywood', 'Wd Shng',
  'BrkFace', 'AsbShng',  'Stucco', 'Brk Cmn',   'Stone',   'Other',  'CBlock',
  'ImStucc', 'AsphShn']
 Length: 16, dtype: str,
 <StringArray>
 ['BrkFace', nan, 'Stone', 'BrkCmn']
 Length: 4, dtype: str,
 <StringArray>
 ['TA', 'Gd', 'Ex', 'Fa']
 Length: 4, dtype: str,
 <StringArray>
 ['Gd', 'TA', 'Fa', 'Po', 'Ex']
 Length: 5, dtype: str,
 <StringArray>
 ['PConc', 'CBlock', 'BrkTil', 'Slab', 'Wood', 'Stone']
 Length: 6, dtype: str,
 <StringArray>
 ['TA', 'Gd', 'Ex', 'Fa', nan]
 Length: 5, dtype: str,
 <StringArray>
 ['TA', 'Gd', 'Fa', nan, 'Po']
 Length: 5, dtype: str,
 <StringArray>
 ['Gd', 'No', 'Av', 'Mn', nan]
 Length: 5, dtype: str,
 <StringArray>
 ['GLQ', 'ALQ', 'Unf', 'BLQ', 'LwQ', 'Rec', nan]
 Length: 7, dtype: str,
 <StringArray>
 ['Unf', 'LwQ', 'BLQ', 'Rec', 'ALQ', nan, 'GLQ']
 Length: 7, dtype: str,
 <StringArray>
 ['GasA', 'Grav', 'GasW', 'OthW', 'Wall', 'Floor']
 Length: 6, dtype: str,
 <StringArray>
 ['Ex', 'TA', 'Gd', 'Fa', 'Po']
 Length: 5, dtype: str,
 <StringArray>
 ['Y', 'N']
 Length: 2, dtype: str,
 <StringArray>
 ['SBrkr', 'FuseA', 'FuseF', 'FuseP', nan]
 Length: 5, dtype: str,
 <StringArray>
 ['Gd', 'TA', 'Ex', 'Fa']
 Length: 4, dtype: str,
 <StringArray>
 ['Typ', 'Maj2', 'Min1', 'Mod', 'Maj1', 'Min2', 'Sev']
 Length: 7, dtype: str,
 <StringArray>
 [nan, 'TA', 'Fa', 'Gd', 'Po', 'Ex']
 Length: 6, dtype: str,
 <StringArray>
 ['Attchd', nan, 'Detchd', 'BuiltIn', 'Basment', 'CarPort', '2Types']
 Length: 7, dtype: str,
 <StringArray>
 ['RFn', nan, 'Unf', 'Fin']
 Length: 4, dtype: str,
 <StringArray>
 ['TA', nan, 'Gd', 'Fa', 'Ex', 'Po']
 Length: 6, dtype: str,
 <StringArray>
 ['TA', nan, 'Fa', 'Po', 'Gd', 'Ex']
 Length: 6, dtype: str,
 <StringArray>
 ['Y', 'N', 'P']
 Length: 3, dtype: str,
 <StringArray>
 [nan, 'Gd', 'Ex', 'Fa']
 Length: 4, dtype: str,
 <StringArray>
 ['MnPrv', nan, 'GdWo', 'GdPrv', 'MnWw']
 Length: 5, dtype: str,
 <StringArray>
 [nan, 'Othr', 'Shed', 'Gar2', 'TenC']
 Length: 5, dtype: str,
 <StringArray>
 ['WD', 'New', 'ConLw', 'ConLD', 'CWD', 'COD', 'Oth', 'ConLI', 'Con']
 Length: 9, dtype: str,
 <StringArray>
 ['Abnorml', 'Partial', 'Normal', 'Family', 'AdjLand', 'Alloca']
 Length: 6, dtype: str]