In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data/train.csv')
cols1 = data.columns
data = data.rename({'1stFlrSF': 'FstFlrSF', 
              '2ndFlrSF': 'SndFlrSF', 
              '3SsnPorch': 'ThirdSsnPorch'}, axis=1)

In [3]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', 'FstFlrSF', 'SndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', 'ThirdSsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='str')

In [4]:
catgeorical_columns = [column for column in data.columns if data[column].dtype == 'str']
quantitive_columns = [column for column in data.columns if data[column].dtype != 'str' and column != "SalePrice"]
print('categorical_columns =', catgeorical_columns)
print('quantitive_columns =', quantitive_columns)

categorical_columns = ['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']
quantitive_columns = ['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'FstFlrSF', 'SndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', 'ThirdSsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']

In [5]:
missing_values = data.isna().sum().sort_values(ascending=False)
missing_values_columns = missing_values[missing_values > 0]
missing_values_columns

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageYrBlt       81
GarageCond        81
GarageType        81
GarageFinish      81
GarageQual        81
BsmtFinType2      38
BsmtExposure      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
dtype: int64

# Preprocessing test

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import TargetEncoder

In [7]:
pd.DataFrame(TargetEncoder(target_type='continuous').fit_transform(data[catgeorical_columns], data.iloc[::, -1]), columns=catgeorical_columns)

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,192525.188365,181900.728516,183856.911202,165891.671164,180380.689411,181673.108132,177701.136756,180361.518854,197089.428949,185969.073847,...,204446.947232,200816.546695,188381.970312,188183.995310,187250.014541,180993.714065,188570.553971,182882.645148,173662.860629,175619.685629
1,190027.785769,180530.182134,182929.110880,163213.510453,179518.937030,180433.398116,180252.520373,179594.268924,239762.526845,141841.549584,...,201282.117091,202482.115398,186540.954587,187295.286084,185790.102410,180318.173873,187171.674945,181416.969042,173919.788195,176683.982419
2,190027.785769,180530.182134,182929.110880,206040.286421,179518.937030,180433.398116,176258.630264,179594.268924,195322.880632,183939.011795,...,201282.117091,202482.115398,186540.954587,187295.286084,185790.102410,180318.173873,187171.674945,181416.969042,173919.788195,176683.982419
3,191342.238305,181761.812900,184181.385214,207940.060887,181103.591020,181548.548669,183307.667363,180840.830657,213219.601603,185053.401936,...,135700.214736,142658.690984,187987.269979,188485.094695,186715.128950,180922.902830,188315.573976,182623.343465,173801.640886,150113.312106
4,192525.188365,181900.728516,183856.911202,205582.543002,180380.689411,181673.108132,176816.098750,180361.518854,324281.462364,185969.073847,...,204446.947232,200816.546695,188381.970312,188183.995310,187250.014541,180993.714065,188570.553971,182882.645148,173662.860629,175619.685629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,190027.785769,180530.182134,182929.110880,163213.510453,179518.937030,180433.398116,176258.630264,179594.268924,193893.018514,183939.011795,...,201282.117091,202482.115398,186540.954587,187295.286084,185790.102410,180318.173873,187171.674945,181416.969042,173919.788195,176683.982419
1456,188978.100709,179255.974379,181358.999528,164643.214005,178248.386517,179039.675616,175483.282817,177775.612855,184444.292124,182242.642908,...,200846.353724,142658.841564,185527.286174,185923.981433,184198.352869,178408.292509,146563.859319,180110.098169,172037.737269,172929.851515
1457,192525.188365,181900.728516,183856.911202,165891.671164,180380.689411,181673.108132,177701.136756,180361.518854,207267.760986,185969.073847,...,204446.947232,200816.546695,188381.970312,188183.995310,187250.014541,180993.714065,174942.734872,149256.441638,173662.860629,175619.685629
1458,190027.785769,180530.182134,182929.110880,163213.510453,179518.937030,180433.398116,176258.630264,179594.268924,145961.844568,183939.011795,...,201282.117091,142035.202840,186540.954587,187295.286084,185790.102410,180318.173873,187171.674945,181416.969042,173919.788195,176683.982419
1459,190027.785769,180530.182134,182929.110880,163213.510453,179518.937030,180433.398116,176258.630264,179594.268924,126004.648588,183939.011795,...,201282.117091,237945.565183,186540.954587,187295.286084,185790.102410,180318.173873,187171.674945,181416.969042,173919.788195,176683.982419

In [8]:
pd.DataFrame(StandardScaler().fit_transform(SimpleImputer(strategy='median').fit_transform(data[quantitive_columns])), columns=quantitive_columns)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,ThirdSsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,-1.730865,0.073375,-0.220875,-0.207142,0.651479,-0.517200,1.050994,0.878668,0.514104,0.575425,...,0.351000,-0.752176,0.216503,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,0.138777
1,-1.728492,-0.872563,0.460320,-0.091886,-0.071836,2.179628,0.156734,-0.429577,-0.570750,1.171992,...,-0.060731,1.626195,-0.704483,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-0.489110,-0.614439
2,-1.726120,0.073375,-0.084636,0.073480,0.651479,-0.517200,0.984752,0.830215,0.325915,0.092907,...,0.631726,-0.752176,-0.070361,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,0.990891,0.138777
3,-1.723747,0.309859,-0.447940,-0.096897,0.651479,-0.517200,-1.863632,-0.720298,-0.570750,-0.499274,...,0.790804,-0.752176,-0.176048,4.092524,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,-1.367655
4,-1.721374,0.073375,0.641972,0.375148,1.374795,-0.517200,0.951632,0.733308,1.366489,0.463568,...,1.698485,0.780197,0.563760,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,2.100892,0.138777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1.721374,0.073375,-0.357114,-0.260560,-0.071836,-0.517200,0.918511,0.733308,-0.570750,-0.973018,...,-0.060731,-0.752176,-0.100558,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,0.620891,-0.614439
1456,1.723747,-0.872563,0.687385,0.266407,-0.071836,0.381743,0.222975,0.151865,0.087911,0.759659,...,0.126420,2.033231,-0.704483,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-1.599111,1.645210
1457,1.726120,0.309859,-0.175462,-0.147810,0.651479,3.078570,-1.002492,1.024029,-0.570750,-0.369871,...,-1.033914,-0.752176,0.201405,-0.359325,-0.116339,-0.270208,-0.068692,4.953112,-0.489110,1.645210
1458,1.728492,-0.872563,-0.084636,-0.080160,-0.795151,0.381743,-0.704406,0.539493,-0.570750,-0.865548,...,-1.090059,2.168910,-0.704483,1.473789,-0.116339,-0.270208,-0.068692,-0.087688,-0.859110,1.645210
1459,1.730865,-0.872563,0.233255,-0.058112,-0.795151,0.381743,-0.207594,-0.962566,-0.570750,0.847389,...,-0.921624,5.121921,0.322190,-0.359325,-0.116339,-0.270208,-0.068692,-0.087688,-0.119110,0.138777

In [9]:
categorical_columns = [
    "MSZoning",
    "Street",
    "Alley",
    "LotShape",
    "LandContour",
    "Utilities",
    "LotConfig",
    "LandSlope",
    "Neighborhood",
    "Condition1",
    "Condition2",
    "BldgType",
    "HouseStyle",
    "RoofStyle",
    "RoofMatl",
    "Exterior1st",
    "Exterior2nd",
    "MasVnrType",
    "ExterQual",
    "ExterCond",
    "Foundation",
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2",
    "Heating",
    "HeatingQC",
    "CentralAir",
    "Electrical",
    "KitchenQual",
    "Functional",
    "FireplaceQu",
    "GarageType",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
    "PavedDrive",
    "PoolQC",
    "Fence",
    "MiscFeature",
    "SaleType",
    "SaleCondition",
]
quantitive_columns = [
    "Id",
    "MSSubClass",
    "LotFrontage",
    "LotArea",
    "OverallQual",
    "OverallCond",
    "YearBuilt",
    "YearRemodAdd",
    "MasVnrArea",
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "FstFlrSF",
    "SndFlrSF",
    "LowQualFinSF",
    "GrLivArea",
    "BsmtFullBath",
    "BsmtHalfBath",
    "FullBath",
    "HalfBath",
    "BedroomAbvGr",
    "KitchenAbvGr",
    "TotRmsAbvGrd",
    "Fireplaces",
    "GarageYrBlt",
    "GarageCars",
    "GarageArea",
    "WoodDeckSF",
    "OpenPorchSF",
    "EnclosedPorch",
    "ThirdSsnPorch",
    "ScreenPorch",
    "PoolArea",
    "MiscVal",
    "MoSold",
    "YrSold",
]

numeric_transformer = Pipeline(steps=[("imputer", SimpleImputer(strategy="median")), ("scaler", StandardScaler())])


categorical_transformer = Pipeline(steps=[("target_enc", TargetEncoder(target_type="continuous", smooth="auto"))])


preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, quantitive_columns),
        ("cat", categorical_transformer, catgeorical_columns),
    ],
    remainder="drop",
)

In [10]:
preprocessor.fit_transform(data.iloc[::, :-1:], data.iloc[::, -1])

array([[-1.73086488e+00,  7.33749635e-02, -2.20875089e-01, ...,
         1.81990998e+05,  1.72951021e+05,  1.74913444e+05],
       [-1.72849220e+00, -8.72562756e-01,  4.60319735e-01, ...,
         1.80706825e+05,  1.72361000e+05,  1.73574772e+05],
       [-1.72611953e+00,  7.33749635e-02, -8.46361241e-02, ...,
         1.82585411e+05,  1.73418404e+05,  1.75680149e+05],
       ...,
       [ 1.72611953e+00,  3.09859393e-01, -1.75462101e-01, ...,
         1.50297231e+05,  1.73418404e+05,  1.75680149e+05],
       [ 1.72849220e+00, -8.72562756e-01, -8.46361241e-02, ...,
         1.82585411e+05,  1.73418404e+05,  1.75680149e+05],
       [ 1.73086488e+00, -8.72562756e-01,  2.33254794e-01, ...,
         1.81990998e+05,  1.72951021e+05,  1.74913444e+05]],
      shape=(1460, 80))

# Import preprocessing pipeline

In [12]:
from preprocessing import preprocessor

# data split

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    data.iloc[::, :-1:], data.iloc[::, -1], test_size=0.33, random_state=42)

In [14]:
X_train.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', 'FstFlrSF', 'SndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', 'ThirdSsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='str')

# Model

In [15]:
from sklearn.ensemble import GradientBoostingRegressor

In [16]:
model_pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', GradientBoostingRegressor())
])

In [17]:
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Id', 'MSSubClass',
                                                   'LotFrontage', 'LotArea',
                                                   'OverallQual', 'OverallCond',
                                                   'YearBuilt', 'YearRemodAdd',
                                                   'MasVnrArea', 'BsmtFinSF1',
                                                   'BsmtFinSF2', 'BsmtUnfSF',
                                                   'TotalBsmtSF', 'FstFlrSF',
                                                   'SndFlrSF', 'L...
                                                   'LotConfig', 'LandSlope',
                                                   'Neighborhood', 'Condition1',
                                                   'Condition2', 'BldgType',
                                                   'HouseStyle', 'RoofStyle',
                                                   'RoofMatl', 'Exterior1st',
                                                   'Exterior2nd', 'MasVnrType',
                                                   'ExterQual', 'ExterCond',
                                                   'Foundation', 'BsmtQual',
                                                   'BsmtCond', 'BsmtExposure',
                                                   'BsmtFinType1',
                                                   'BsmtFinType2', 'Heating',
                                                   'HeatingQC', 'CentralAir',
                                                   'Electrical', ...])])),
                ('model', GradientBoostingRegressor())])

In [18]:
preds = model_pipeline.predict(X_test)
preds

array([142989.88491668, 347777.81405149, 119775.04543041, 137777.55267428,
       324011.17156158,  80398.65718878, 221236.3903131 , 137306.4647469 ,
        78329.61405407, 131471.23346792, 147201.78189578, 125343.25145144,
       126449.46159976, 204377.67869227, 172586.98072337, 134917.49886122,
       195404.86068274, 136949.03625776, 112868.48806023, 215892.77551037,
       171762.26153056, 223871.05577787, 174060.88525935, 126759.42798838,
       198819.61544377, 162220.1228442 , 195298.09424184, 121700.51373481,
       178918.94327425, 187026.61791908, 121239.70234272, 259008.40982118,
       222123.00596542, 112000.95581816, 250480.12210919, 153212.3726558 ,
       134291.75520016, 211401.18399417, 323782.69515304,  89647.65039257,
       126437.15626644, 238583.58608964, 120375.72166227, 362699.28369921,
       125216.16738826, 125341.20687686, 117912.99182557, 125461.32214663,
       430245.49850007, 133783.19199226, 122179.61663814, 199083.1771379 ,
       112077.58572858, 338683.67038172, 156342.21518367, 246563.46020663,
       188810.73790375, 149626.51408862, 134686.1326432 , 104732.40403849,
        69421.8774613 , 161408.24339767, 307105.80625194, 280326.27442488,
       295404.71179532, 209126.9613077 , 106332.29500995, 332828.25445619,
       110770.97303125, 162169.12933072, 132171.80358211, 120416.32445746,
       111873.37533703,  85327.5094463 , 456047.28473248, 185105.93914415,
       310344.61100879, 307575.84576257, 138830.97339494, 125396.37456826,
       109314.89973962,  79046.61366359, 130089.63450617,  96201.94488273,
       147199.30386206, 132670.24569581, 267747.30555938, 214022.09490996,
       147917.54827393, 178633.62692064, 146200.7893572 , 162279.22602909,
       125755.47203634, 260496.88197665, 123005.41173159, 181994.04831636,
       174756.36526866, 175030.11550837, 209243.84197291, 244533.18007353,
       164071.4844523 , 205168.91315762, 241541.7741319 , 143265.98220761,
       199470.28174012, 153688.45582436, 150693.94516622, 286513.30167782,
       143734.74133014, 159652.54623163,  49553.89876056, 131196.09770171,
       131679.60659117, 123984.42691473, 196953.40980832, 122792.64171113,
       107031.64538196, 115532.13282388, 129200.77828304, 262797.88803262,
       139571.28455771, 146913.63342297, 176975.82186409, 174278.56693157,
       184161.29863649, 130528.1677402 , 243766.1722853 , 103565.52970371,
       152898.03493089, 182487.65586102, 190928.73504565, 369609.65472297,
       194467.32941294, 127464.94140503,  63494.15190092, 364475.31933306,
       424585.71177363, 139218.838665  , 231047.86298485, 530248.11764181,
       316812.22246963, 135094.27119852, 178496.83612318, 150221.6220587 ,
       142266.79590853, 124211.95590277, 235516.98803842, 194942.83664734,
       135030.8646638 ,  69140.89136669, 118422.13538026, 146929.90865853,
       263604.97716415, 145682.5687621 ,  90630.72086402, 115751.79004086,
       142326.11695449, 143635.83164641,  94001.84808135, 130408.51774827,
       222006.22500548, 142483.97433643, 303722.07456779, 141871.98752708,
       115069.43243695, 119640.84508771, 215276.17123239, 380002.15460042,
       451232.90608841, 249607.03074027, 385858.62394813,  92549.10597494,
       114921.96340026, 144473.37193924, 390262.54584043, 153103.68082376,
       118051.2314753 , 208751.22112095, 122204.64474708, 161328.06605522,
       176296.90670481, 101707.39412227, 136607.50115728, 138516.01326471,
       259099.07791893, 145360.7066916 , 272835.45603548, 212446.83367791,
       184589.55927964,  83226.35212109, 114974.60672597, 112608.06710868,
       146678.0633823 , 144751.402128  , 176115.37063259, 172763.83231335,
       234730.93620767,  82350.32461711, 207066.9719667 , 137738.06556061,
       218926.07093853, 190001.90210496, 123859.20742049, 349034.33497145,
       188143.33575879, 125555.70222504, 239110.40361575, 135045.11669429,
       151835.55701526, 119993.61362187, 234977.78173457, 138933.52114598,
       117693.65101067, 156523.2964855 , 207747.22463411, 275248.80018545,
       191169.16107492, 145199.75323888, 141663.58329892, 144680.03105833,
       140076.85534168, 224114.64903456, 212922.10282921, 102700.61902327,
       255677.9095794 , 152597.41710014, 102137.48844599,  99577.70452055,
       174202.95171097, 108334.0613187 , 103675.29340647, 183953.97794037,
       123220.62040909, 141030.67675168, 218478.98962934, 132098.85134057,
       197845.02166625, 149201.54985464, 227199.74347059, 133857.16445384,
       114266.00924984, 268252.13177878, 208370.02525609, 389064.45711078,
       200163.25153353, 133051.4437851 , 156486.80082782, 178774.4241707 ,
       143677.84657995, 100858.11222294, 191223.11724973, 174915.13508535,
       128407.35499673, 107391.31337599, 133044.0131939 , 143997.52719429,
       110171.64389087, 103066.27022629, 169582.20367529, 264776.86932838,
       313161.31688109, 174346.194137  , 142007.42518216, 230349.66171975,
       306800.07098628, 207356.91277448, 163409.76246352, 142100.10766608,
       119421.94102362, 174162.10358994, 399819.87856781, 241599.96785731,
       226528.45449082,  91717.40505992, 108084.73852276, 131616.61060585,
       144075.31882763, 290393.33390673, 251728.79082311, 139073.71567936,
       197808.36017076, 105059.630218  , 189802.89787189, 112152.93479175,
       316808.26393353, 183349.93459959, 210041.9642531 , 148959.08873801,
       255643.0096204 , 186242.97381297, 110201.70012925, 119136.06435036,
       146377.66251077, 179494.78111825, 104808.17394652, 141627.72007896,
       135869.92248016, 145871.49496346, 182325.50789406, 114899.23877312,
       185193.05704387, 233248.83222002, 120547.44841739, 150025.19719141,
       176203.3406268 , 194123.43716644, 159904.06438228, 225706.74623766,
       241557.27629526, 125354.62323818, 140041.59170573, 206107.70578481,
       114368.30274795, 167715.50812311, 128074.94811308, 184871.58577739,
       181374.99746414, 163369.51323555, 280276.13126807,  85327.5094463 ,
       225816.43163996, 147330.11252132, 130865.7883509 ,  95395.67531342,
       188646.85270898, 166917.71469699, 122467.01614889, 191792.55166529,
       158695.01388813, 105415.0274431 , 152866.83339416, 144245.80561827,
       132869.79505309, 204452.76300958, 161237.59959162, 129394.39587298,
       129539.59558374,  94082.66179967,  89767.81698489, 213523.01625372,
       181421.64854159, 134068.80096271, 134239.89060587, 185502.12499626,
       220173.35182294, 336745.12089607, 350670.73827179, 120324.40086856,
       239678.32900873, 120942.51476745, 322418.86434031, 412189.29519929,
       295866.73851392, 160077.31093696, 262003.10820735, 141632.14974167,
       126531.45015346,  91420.67279431, 199998.27945274, 348567.42777231,
       207732.57996894, 137825.15412276, 255601.24836957, 226452.61133971,
       131268.20918823, 190292.70771315, 169500.38718461, 104700.07899443,
       132902.78244683, 153198.92842031, 120197.2133498 , 177830.30796695,
       125285.07274319, 211830.49365698, 151536.81881719, 127732.76695787,
       215085.64803588, 194160.48606419,  93645.89467949, 210193.45134778,
       141963.06179987, 189230.54050686, 186076.59121543, 166690.8415592 ,
       139736.86060526, 220343.18203034, 140151.16454751, 109870.9317268 ,
       300894.26724573, 167719.89995702, 121895.76345059, 163531.58823764,
       132386.72278083, 365432.83235428, 147540.73310827, 403646.82083055,
       122578.85910303, 176877.31011228, 165340.50962655, 142861.00578207,
       168201.72179596, 382911.24030921, 114163.95925372, 148136.77672922,
       148485.32860795, 101896.34893295, 198109.74281859, 154075.55686434,
       250543.00985664, 205538.88881215, 217490.551408  , 211626.67414079,
        76157.17246592, 336568.80667338, 140729.65727361, 350495.56186758,
       140612.90130496, 371090.49836081, 275566.35108936, 124891.17264833,
       228012.71665526, 241824.29060397, 205538.88881215, 180602.47437716,
       256896.65336546, 111836.44362147, 214876.81921285, 173691.45464194,
       190909.27187832, 234630.87001909, 110382.70013077, 162541.81982425,
       183251.54812755, 141369.06892703, 124527.20886752, 194171.49702997,
       132821.38909263, 448609.89692872, 180381.14830242, 129308.94987572,
       207006.14088087, 321649.2931134 , 202693.89306668, 153396.62608642,
       195174.81701652, 137195.96124278, 183795.17220375, 214506.3872678 ,
       134530.50526116, 145703.94982546, 121522.57751328, 169451.73427928,
       242371.99375717, 167719.89779456,  95148.87235609, 212034.22227328,
       335188.16200204, 335901.23099114, 254377.66214959, 155044.75461472,
       131883.26430195, 112501.80883033, 173318.78104673, 226735.37197091,
       166515.44207072, 447015.31140363, 192147.88179877, 190292.70771315,
       120025.58635762, 267664.55332505, 117635.67062936, 109439.6933353 ,
       131778.79663165, 123954.57224098, 205803.71033963, 255609.34368866,
       126919.2639413 , 115982.88724978, 116261.31694725, 216023.18860492,
       143489.62445287, 170506.75408914])

In [19]:
abs(np.log(y_test) - np.log(preds)).mean()

np.float64(0.09122773796704936)

# Saving model

In [20]:
import joblib

metadata = {
    'version': '1.0.0',
    'features': X_train.columns
}

bundle = {
    "pipeline": model_pipeline,
    "metadata": metadata
}

joblib.dump(bundle, "../artifact/model_1.0.joblib")

['../artifact/model_1.0.joblib']

In [21]:
_ = [print(i, ':', X_train[i].dtype) for i in X_train.columns.to_list()]

Id : int64
MSSubClass : int64
MSZoning : str
LotFrontage : float64
LotArea : int64
Street : str
Alley : str
LotShape : str
LandContour : str
Utilities : str
LotConfig : str
LandSlope : str
Neighborhood : str
Condition1 : str
Condition2 : str
BldgType : str
HouseStyle : str
OverallQual : int64
OverallCond : int64
YearBuilt : int64
YearRemodAdd : int64
RoofStyle : str
RoofMatl : str
Exterior1st : str
Exterior2nd : str
MasVnrType : str
MasVnrArea : float64
ExterQual : str
ExterCond : str
Foundation : str
BsmtQual : str
BsmtCond : str
BsmtExposure : str
BsmtFinType1 : str
BsmtFinSF1 : int64
BsmtFinType2 : str
BsmtFinSF2 : int64
BsmtUnfSF : int64
TotalBsmtSF : int64
Heating : str
HeatingQC : str
CentralAir : str
Electrical : str
FstFlrSF : int64
SndFlrSF : int64
LowQualFinSF : int64
GrLivArea : int64
BsmtFullBath : int64
BsmtHalfBath : int64
FullBath : int64
HalfBath : int64
BedroomAbvGr : int64
KitchenAbvGr : int64
KitchenQual : str
TotRmsAbvGrd : int64
Functional : str
Fireplaces : int64
FireplaceQu : str
GarageType : str
GarageYrBlt : float64
GarageFinish : str
GarageCars : int64
GarageArea : int64
GarageQual : str
GarageCond : str
PavedDrive : str
WoodDeckSF : int64
OpenPorchSF : int64
EnclosedPorch : int64
ThirdSsnPorch : int64
ScreenPorch : int64
PoolArea : int64
PoolQC : str
Fence : str
MiscFeature : str
MiscVal : int64
MoSold : int64
YrSold : int64
SaleType : str
SaleCondition : str

In [25]:
loaded_model = joblib.load("../artifact/model_1.0.joblib")

In [26]:
loaded_model

{'pipeline': Pipeline(steps=[('preprocessing',
                  ColumnTransformer(transformers=[('num',
                                                   Pipeline(steps=[('imputer',
                                                                    SimpleImputer(strategy='median')),
                                                                   ('scaler',
                                                                    StandardScaler())]),
                                                   ['Id', 'MSSubClass',
                                                    'LotFrontage', 'LotArea',
                                                    'OverallQual', 'OverallCond',
                                                    'YearBuilt', 'YearRemodAdd',
                                                    'MasVnrArea', 'BsmtFinSF1',
                                                    'BsmtFinSF2', 'BsmtUnfSF',
                                                    'TotalBsmtSF', 'FstFlrSF',
                                                    'SndFlrSF', 'L...
                                                    'LotConfig', 'LandSlope',
                                                    'Neighborhood', 'Condition1',
                                                    'Condition2', 'BldgType',
                                                    'HouseStyle', 'RoofStyle',
                                                    'RoofMatl', 'Exterior1st',
                                                    'Exterior2nd', 'MasVnrType',
                                                    'ExterQual', 'ExterCond',
                                                    'Foundation', 'BsmtQual',
                                                    'BsmtCond', 'BsmtExposure',
                                                    'BsmtFinType1',
                                                    'BsmtFinType2', 'Heating',
                                                    'HeatingQC', 'CentralAir',
                                                    'Electrical', ...])])),
                 ('model', GradientBoostingRegressor())]),
 'metadata': {'version': '1.0.0',
  'features': Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
         'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
         'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
         'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
         'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
         'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
         'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
         'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
         'HeatingQC', 'CentralAir', 'Electrical', 'FstFlrSF', 'SndFlrSF',
         'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
         'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
         'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
         'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
         'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
         'EnclosedPorch', 'ThirdSsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
         'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
         'SaleCondition'],
        dtype='str')}}

In [46]:
print(loaded_model['pipeline'].predict(X_test.head(1)),
loaded_model['pipeline'].predict(X_test.head(1)))

[142989.88491668] [142989.88491668]

# Example for fastapi test

In [44]:
_ = [print(f'"{key}" : "{value}",') if isinstance(value, str) else print(f'"{key}" : {value},')  for (key, value) in zip(X_train.columns, X_train.loc[0])]

"Id" : 1,
"MSSubClass" : 60,
"MSZoning" : "RL",
"LotFrontage" : 65.0,
"LotArea" : 8450,
"Street" : "Pave",
"Alley" : nan,
"LotShape" : "Reg",
"LandContour" : "Lvl",
"Utilities" : "AllPub",
"LotConfig" : "Inside",
"LandSlope" : "Gtl",
"Neighborhood" : "CollgCr",
"Condition1" : "Norm",
"Condition2" : "Norm",
"BldgType" : "1Fam",
"HouseStyle" : "2Story",
"OverallQual" : 7,
"OverallCond" : 5,
"YearBuilt" : 2003,
"YearRemodAdd" : 2003,
"RoofStyle" : "Gable",
"RoofMatl" : "CompShg",
"Exterior1st" : "VinylSd",
"Exterior2nd" : "VinylSd",
"MasVnrType" : "BrkFace",
"MasVnrArea" : 196.0,
"ExterQual" : "Gd",
"ExterCond" : "TA",
"Foundation" : "PConc",
"BsmtQual" : "Gd",
"BsmtCond" : "TA",
"BsmtExposure" : "No",
"BsmtFinType1" : "GLQ",
"BsmtFinSF1" : 706,
"BsmtFinType2" : "Unf",
"BsmtFinSF2" : 0,
"BsmtUnfSF" : 150,
"TotalBsmtSF" : 856,
"Heating" : "GasA",
"HeatingQC" : "Ex",
"CentralAir" : "Y",
"Electrical" : "SBrkr",
"FstFlrSF" : 856,
"SndFlrSF" : 854,
"LowQualFinSF" : 0,
"GrLivArea" : 1710,
"BsmtFullBath" : 1,
"BsmtHalfBath" : 0,
"FullBath" : 2,
"HalfBath" : 1,
"BedroomAbvGr" : 3,
"KitchenAbvGr" : 1,
"KitchenQual" : "Gd",
"TotRmsAbvGrd" : 8,
"Functional" : "Typ",
"Fireplaces" : 0,
"FireplaceQu" : nan,
"GarageType" : "Attchd",
"GarageYrBlt" : 2003.0,
"GarageFinish" : "RFn",
"GarageCars" : 2,
"GarageArea" : 548,
"GarageQual" : "TA",
"GarageCond" : "TA",
"PavedDrive" : "Y",
"WoodDeckSF" : 0,
"OpenPorchSF" : 61,
"EnclosedPorch" : 0,
"ThirdSsnPorch" : 0,
"ScreenPorch" : 0,
"PoolArea" : 0,
"PoolQC" : nan,
"Fence" : nan,
"MiscFeature" : nan,
"MiscVal" : 0,
"MoSold" : 2,
"YrSold" : 2008,
"SaleType" : "WD",
"SaleCondition" : "Normal",